# Generated by Django 4.0.4 on 2022-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_works',
            field=models.TextField(default=0, verbose_name='Выполненные работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='days_of_the_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], default='Пн', max_length=2),
        ),
    ]
