# Generated by Django 4.0.4 on 2022-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_student_completed_works_student_days_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visiting_time',
            field=models.DateTimeField(verbose_name='Время посещения'),
        ),
    ]
