# Generated by Django 4.0.4 on 2022-05-14 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0006_alter_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Work',
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['full_name'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
    ]
