# Generated by Django 4.0.4 on 2022-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_rename_student_work_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['full_name'], 'verbose_name': 'Работу', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='work',
            name='completed_works_file',
            field=models.FileField(blank=True, upload_to='completed_works/', verbose_name='Файл выполненных работ'),
        ),
    ]
