# Generated by Django 4.0.4 on 2022-05-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_work_options_work_completed_works_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='completed_works_file',
        ),
    ]
